version: '3'
services:
  postgres:
    image: 'postgres:15.5'
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - main_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  migrations:
    build: 
      context: ./app/db
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - main_network
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - main_network
networks:
  main_network:
