version: '3'
services:
  postgres:
    image: 'postgres:15.5'
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 9000:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - main_network
    volumes:
      - db_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    build: ./app
    env_file: .env
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    stop_signal: SIGINT
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - main_network
networks:
  main_network:
volumes:
  db_data: