"""Initial commit

Revision ID: 38b8ee8c7ddf
Revises: 
Create Date: 2024-05-01 14:03:02.479613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b8ee8c7ddf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.CheckConstraint('length(description) < 1000', name='description_valid_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(), nullable=False),
    sa.CheckConstraint('length(genre_name) < 60', name='genre_valid_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre_name', name='genre_name_unique_constraint')
    )
    op.create_table('movie',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('movie_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('poster', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.CheckConstraint('length(description) < 1000', name='description_valid_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_actor',
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    op.create_table('movie_genre',
    sa.Column('movie_id', sa.String(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_genre')
    op.drop_table('movie_actor')
    op.drop_table('movie')
    op.drop_table('genre')
    op.drop_table('actor')
    # ### end Alembic commands ###
